branches:
  except:
    - dev
language:
  - android
jdk:
  - openjdk7
android:
  components:
    - build-tools-20.0.0
    - android-20

before_install:
  # for gradle output style
  - export TERM=dumb
  # newest Android NDK
  - if [ `uname -m` = x86_64 ]; then wget http://dl.google.com/android/ndk/android-ndk-r9d-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-r9d-linux-x86.tar.bz2 -O ndk.tgz; fi
  - tar -xf ndk.tgz
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r9d
  - export PATH=${PATH}:${ANDROID_NDK_HOME}

script:
  - ./gradlew build --info
